import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import StoreProvider from "@/providers/StoreProvider";
import AuthProvider from "@/providers/authProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TokenProvider from "@/providers/TokenProvider";
import { poppins } from "./utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <StoreProvider>
          <AuthProvider>
            <TokenProvider>
              <ReactQueryProvider>
                <Navbar />
                {children}
              </ReactQueryProvider>
              <Footer />
              <ToastContainer />
            </TokenProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
